version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: auto-crm-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: auto-crm-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: auto-crm-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: auto_crm
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
