version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
    image: auto-crm-app
    container_name: auto-crm-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./storage:/var/www/storage
      - ./docker/nginx/ssl:/etc/nginx/ssl
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
