version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
    image: auto-crm-app
    container_name: auto-crm-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./storage:/var/www/storage
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_www:/var/www/certbot
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: auto-crm-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/public
      - ./storage/app/public:/var/www/public/storage
      - ./docker/nginx/default-production-ssl.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_www:/var/www/certbot
    depends_on:
      - app
    networks:
      - laravel

  certbot:
    image: certbot/certbot
    container_name: auto-crm-certbot
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_www:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${DOMAIN_NAME} --force-renewal
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: auto-crm-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: autocrm
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: autocrm
      MYSQL_PASSWORD: autocrm
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel
volumes:
  dbdata:
  letsencrypt_certs:
  letsencrypt_www:

networks:
  laravel:
    driver: bridge
