version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
    image: auto-crm-app
    container_name: auto-crm-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./storage:/var/www/storage
    depends_on:
      - mysql
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: auto-crm-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public
      - ./storage/app/public:/var/www/public/storage
      - ./docker/nginx/default-production.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: auto-crm-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: autocrm
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: autocrm
      MYSQL_PASSWORD: autocrm
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
