version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
    image: auto-crm-app
    container_name: auto-crm-app
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/storage
    depends_on:
      - mysql
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: auto-crm-nginx
    ports:
      - "80:80"
    volumes:
      - ./storage/app/public:/var/www/public/storage
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: auto-crm-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: auto_crm
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
